name: flutter_application_4
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/your_app_logo.png

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.12.0
  onesignal_flutter: ^5.0.0  # or the latest version
  http: ^0.13.3 # Use the latest compatible version
  firebase_database: ^10.1.0
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.8
  firebase_messaging: ^14.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
